INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (3,'A Cañiza',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (5,'A Estrada',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (7,'A Guarda',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (21,'Campo Lameiro',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (26,'Catoira',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (32,'Cuntis',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (37,'Lalín',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (41,'Marín',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (43,'Moaña',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (52,'O Porriño',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (58,'Poio',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (59,'Ponteareas',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (61,'Pontevedra',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (64,'Redondela',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (97,'Redondela 2',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (75,'Tomiño',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (76,'Tui',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (77,'Valga',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (81,'Vigo',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (82,'Vilagarcía',36);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (83,'Vilanova de Arousa',36);

INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (4,'A Coruña - BPMGG',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (101,'A Coruña - CENTRO CÍVICO DE EIRIS',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (1,'Abegondo',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (9,'Ames',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (10,'Ares',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (11,'Arzúa',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (12,'As Pontes',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (15,'Betanzos',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (17,'Boiro',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (18,'Brión',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (20,'Camariñas',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (24,'Carballo',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (103,'CDTIC - Centro Demostrador TIC',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (29,'Cerceda',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (31,'Corcubión',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (33,'Ferrol',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (34,'Fisterra',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (42,'Melide',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (46,'Mugardos',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (47,'Muros',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (48,'Narón',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (49,'Negreira',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (50,'Noia',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (53,'Oroso',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (54,'Ortigueira',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (57,'Padrón',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (60,'Pontedeume',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (62,'Porto do Son',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (67,'Ribeira',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (69,'Sada',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (70,'San Sadurniño',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (71,'Santa Comba',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (72,'Santiago',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (78,'Vedra',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (85,'Vilasantar',15);
INSERT INTO `aulas` (`id`,`name`,`provincia_id`) VALUES (86,'Vimianzo',15);

INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (2,'A Bola',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (8,'Allariz',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (92,'Bande',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (13,'Beariz',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (16,'Boborás',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (22,'Carballiño',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (25,'Castrelo de Miño',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (27,'Castro Caldelas',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (28,'Celanova',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (38,'Leiro',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (40,'Manzaneda',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (51,'O Barco',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (55,'Ourense',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (65,'Ribadavia',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (94,'Ribeiro',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (73,'Sarreaus',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (79,'Verín',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (80,'Viana do Bolo',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (84,'Vilar de Santos',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (88,'Xinzo de Limia',32);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (89,'Xunqueira de Ambía',32);

INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (6,'A Fonsagrada',27);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (93,'Barreiros',27);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (14,'Becerreá',27);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (19,'Burela',27);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (23,'Carballedo',27);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (30,'Chantada',27);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (35,'Foz',27);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (36,'Guitiriz',27);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (39,'Lugo - O Castiñeiro',27);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (96,'Lugo 2 - María Balteira',27);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (44,'Monforte',27);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (45,'Monterroso',27);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (56,'O Vicedo',27);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (63,'Quiroga',27);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (66,'Ribadeo',27);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (68,'Riotorto',27);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (74,'Sarria',27);
INSERT INTO `aulas` (`id`, `name`, `provincia_id`) VALUES (87,'Viveiro',27);
