version: "2"
services:
    www:
        build: php/.
        ports: 
            - "8002:80"
        volumes:
            - 'C:\Users\ingjr\Proyectos\php\cemitcriket\src:/var/www/html/'
        links:
            - db
        networks:
            - default
    scrap:
        image: python
        volumes:
            - 'C:\Users\ingjr\Proyectos\php\cemitcriket\src2:/root'
        links:
            - db
        networks:
            - default
        tty: true
    db:
        image: mysql
        ports: 
            - "3307:3306"
        environment:
            MYSQL_DATABASE: analizerdb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8003:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
volumes:
    persistent: